>>> mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
>>> mul([1],[])
Traceback (most recent call last):
ValueError: shapes (1,) and (0,) not aligned: 1 (dim 0) != 0 (dim 0)

>>> mul([[]], [[]])
Traceback (most recent call last):
ValueError: shapes (1,0) and (1,0) not aligned: 0 (dim 1) != 1 (dim 0)

>>> mul([[1]],[])
Traceback (most recent call last):
ValueError: shapes (1,1) and (0,) not aligned: 1 (dim 1) != 0 (dim 0)

>>> mul([[1], [2, 3]], [[2, 3], [4, 5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> mul([[1, 2], [2, 3]], [[3], [4, 5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> mul([[1, 2], ["2", 3]], [[3, 5], [4, 5]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> mul([[1, 2], [2, 3]], [[3, '5'], [4, 5]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> mul([[1]], [[2,3], [4,5]])
Traceback (most recent call last):
ValueError: shapes (1,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

>>> mul([[1,2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])

>>> mul([[1.5,2], [3.2, 4]], [[1, 2], [3, 4]])
array([[ 7.5, 11. ],
       [15.2, 22.4]])

>>> mul(1, [[1]])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> mul([[1]], 3)
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead
